name: Galleon Pack Template Java CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  # This just runs mvn install like a user would on cloning the repository
  wildfy-21:
    name: WildFly 21

    runs-on: ubuntu-latest

    # The pom is set up for WildFly 21 so we don't need to do anything special
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and Test
        run: |
          mvn --version
          mvn -B install -Dqs.test

      - name: Zip Artifacts
        run: zip -R artifacts.zip 'server.log' 'surefire-reports/*.txt' 'surefire-reports/*.xml'

      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-mp-reactive-raw-{{job.container.id}}
          name: ci-artifacts-mp-reactive-21
          path: artifacts.zip


  wildfly-20:
    # This adjusts the build to use the versions from wildfly master
    name: Against WildFly master

    runs-on: ubuntu-latest

    env:
      WILDFLY_VERSION: 20.0.0.Final
      WILDFLY_CORE_VERSION: 12.0.1.Final
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and Test
        run: |
          mvn --version
          mvn -B install -Dversion.org.wildfly=${WILDFLY_VERSION} -Dversion.org.wildfly.core=${WILDFLY_CORE_VERSION} -Dqs.test

      - name: Zip Artifacts
        run: zip -R artifacts.zip 'server.log' 'surefire-reports/*.txt' 'surefire-reports/*.xml'

      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-mp-reactive-wf-master-{{job.container.id}}
          name: ci-artifacts-mp-reactive-wf-20
          path: artifacts.zip
